version: "3"
services:
    
  jupyter:
    platform: linux/x86_64
    build:
      context: ./docker/ 
      dockerfile: Dockerfile
      network: host      
      args:
         NB_USER: "${user}"
    user: root
    image: local_image/jupyter     
    working_dir: /home/${user}/work
    ports:
      - "${app_ports}" 
    volumes: 
    - type: bind
      source: ${notebook_folder}
      target: /home/${user}/work
    privileged: true   
      
    environment: 
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R    
      - restartable=yes 
      - TZ=${timezone} 
      - DOCKER_STACKS_JUPYTER_CMD=notebook
      - NB_USER=${user}
    #stdin_open: true
    #tty: true
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''" 
  

